# stats_helpers.R — helper functions for exporting stats to LaTeX macros
#
# Usage:
#   source(here("analysis/stats_helpers.R"))
#   set_stats_file("study_1")    # each script sets its own output file
#   write_stat("studyOneN", 59)
#   write_stat("studyOneAgeMean", 33.0, digits = 1)

library(here)

STATS_FILE <- NULL

#' Set the output file for this study (each study gets its own file)
#' @param study_name e.g. "study_1", "study_2", "sensitivity"
set_stats_file <- function(study_name) {
  STATS_FILE <<- here(paste0("analysis/stats_", study_name, ".tex"))
  writeLines(
    paste0("% Auto-generated by analysis/", study_name, ".R — do not edit by hand"),
    STATS_FILE
  )
}

#' Append a \\newcommand to the stats file
#'
#' @param name Command name (without backslash), e.g. "studyOneN"
#' @param value The value to write
#' @param digits Number of decimal places (NULL = write as-is)
write_stat <- function(name, value, digits = NULL) {
  if (!is.null(digits)) {
    formatted <- formatC(value, format = "f", digits = digits)
  } else if (is.numeric(value)) {
    formatted <- as.character(value)
  } else {
    formatted <- as.character(value)
  }
  line <- sprintf("\\providecommand{\\%s}{%s}", name, formatted)
  cat(line, "\n", file = STATS_FILE, append = TRUE)
}

#' Write a p-value as a macro, including the relation symbol (= or <)
write_p <- function(name, p) {
  if (p < 0.001) {
    write_stat(name, "< 0.001")
  } else {
    write_stat(name, paste0("= ", formatC(p, format = "f", digits = 3)))
  }
}

#' Write demographic stats from a demographics dataframe
#'
#' @param prefix e.g. "studyOne"
#' @param demographics_df dataframe with columns: gender, age
#' @param n_subjects number of subjects after exclusions
write_demographics <- function(prefix, demographics_df, n_subjects) {
  write_stat(paste0(prefix, "N"), n_subjects)

  gender_counts <- demographics_df |> count(gender)
  for (g in c("female", "male", "nonconforming")) {
    row <- gender_counts |> filter(gender == g)
    n_g <- if (nrow(row) > 0) row$n else 0
    label <- switch(g,
      female = "Female",
      male = "Male",
      nonconforming = "Nonbinary"
    )
    write_stat(paste0(prefix, "N", label), n_g)
  }

  age_stats <- demographics_df |>
    summarize(
      mean = mean(age),
      sd = sd(age),
      min = min(age),
      max = max(age)
    )
  write_stat(paste0(prefix, "AgeMean"), age_stats$mean, digits = 1)
  write_stat(paste0(prefix, "AgeSD"), age_stats$sd, digits = 1)
  write_stat(paste0(prefix, "AgeMin"), age_stats$min)
  write_stat(paste0(prefix, "AgeMax"), age_stats$max)
}

#' Write a contrast result (diff, CI, t/z, df, p) from an emmeans summary row
#'
#' @param prefix e.g. "studyOnePrecVsRecipAsym"
#' @param row a single row from emmeans summary(infer = T)
#' @param stat_type "t" or "z"
write_contrast <- function(prefix, row, stat_type = "t") {
  write_stat(paste0(prefix, "Diff"), row$estimate, digits = 2)
  write_stat(paste0(prefix, "SE"), row$SE, digits = 2)
  write_stat(paste0(prefix, "CILower"), row$lower.CL, digits = 2)
  write_stat(paste0(prefix, "CIUpper"), row$upper.CL, digits = 2)
  if (stat_type == "t") {
    write_stat(paste0(prefix, "T"), row$t.ratio, digits = 2)
    write_stat(paste0(prefix, "DF"), round(row$df, 0))
  } else {
    write_stat(paste0(prefix, "Z"), row$z.ratio, digits = 2)
  }
  write_p(paste0(prefix, "P"), row$p.value)
}

#' Write an EMM estimate (mean, SE, CI) from an emmeans summary row
#'
#' @param prefix e.g. "studyOneRecipNoInfo"
#' @param row a single row from emmeans summary
write_emm <- function(prefix, row) {
  emm_col <- if ("emmean" %in% names(row)) "emmean" else "the.emmean"
  write_stat(paste0(prefix, "Mean"), row[[emm_col]], digits = 2)
  write_stat(paste0(prefix, "SE"), row$SE, digits = 2)
  if ("lower.CL" %in% names(row)) {
    write_stat(paste0(prefix, "CILower"), row$lower.CL, digits = 2)
    write_stat(paste0(prefix, "CIUpper"), row$upper.CL, digits = 2)
  } else if ("asymp.LCL" %in% names(row)) {
    write_stat(paste0(prefix, "CILower"), row$asymp.LCL, digits = 2)
    write_stat(paste0(prefix, "CIUpper"), row$asymp.UCL, digits = 2)
  }
}

#' Write a Cohen's d effect size
write_cohens_d <- function(prefix, d_value) {
  write_stat(paste0(prefix, "D"), d_value, digits = 2)
}

#' Write odds ratio + CI
write_or <- function(prefix, or_value, ci_lower, ci_upper) {
  write_stat(paste0(prefix, "OR"), or_value, digits = 2)
  write_stat(paste0(prefix, "ORCILower"), ci_lower, digits = 2)
  write_stat(paste0(prefix, "ORCIUpper"), ci_upper, digits = 2)
}

#' Export odds ratio + Wald CI from a glmer model coefficient
export_glmer_or <- function(prefix, mod, coef_name) {
  or <- exp(fixef(mod)[coef_name])
  ci <- exp(confint(mod, parm = coef_name, method = "Wald"))
  write_or(prefix, or, ci[1], ci[2])
}

#' Write a Bayes Factor
write_bf <- function(prefix, bf_value) {
  write_stat(paste0(prefix, "BF"), bf_value, digits = 2)
}

#' Write a fixed-effect coefficient from an lmer model
#'
#' @param prefix e.g. "studyTwoHigherBenefit"
#' @param mod an lmer model
#' @param coef_name name of the fixed effect to export
export_lmer_coef <- function(prefix, mod, coef_name = "diff") {
  coefs <- summary(mod)$coefficients
  row <- coefs[coef_name, ]
  write_stat(paste0(prefix, "B"), row["Estimate"], digits = 2)
  write_stat(paste0(prefix, "T"), row["t value"], digits = 2)
  write_stat(paste0(prefix, "DF"), round(row["df"], 2))
  write_p(paste0(prefix, "P"), row["Pr(>|t|)"])
}

#' Write a fixed-effect coefficient from a glmer model
#'
#' @param prefix e.g. "studyFourEffort"
#' @param mod a glmer model
#' @param coef_name name of the fixed effect to export
export_glmer_coef <- function(prefix, mod, coef_name) {
  coefs <- summary(mod)$coefficients
  row <- coefs[coef_name, ]
  write_stat(paste0(prefix, "B"), row["Estimate"], digits = 2)
  write_stat(paste0(prefix, "Z"), row["z value"], digits = 2)
  write_p(paste0(prefix, "P"), row["Pr(>|z|)"])
}

#' Write a section header comment in the stats file
write_section <- function(label) {
  cat(sprintf("\n%% --- %s ---\n", label), file = STATS_FILE, append = TRUE)
}
